** TDT4255 Exercise 0: Introduction to Chisel and HDLs

This is the exercise 0 chisel intro for the TDT4255 course at NTNU. You may also be here if you are taking TDT4295.

The main content of this repository was originally created by [[https://github.com/PeterAaser][Peter Aaser]]. The content has been adapted slightly for the Fall 2020 version of the course.

There are several separate modules for you to read through before you will be ready
to start writing code.
However, if you just want to get started right away you can skip the introduction
to hardware description languages, and jump straight to the [[./introduction.org][Intro to chisel]] which
covers the practical steps necessary to build your first circuits.
In order to get started you should go through the introductory material:
- [[./hdl.org][Introduction to hardware description languages]]
- [[./introduction.org][Introduction to hardware chisel]]

The deliverable for this exercise is constructing a matrix multiplying unit:
- [[./exercise.org][Matrix multiplier exercise]]
